### ISSUE TITLE
Project fails to load files

### ISSUE THREAD

**Issue by septIO** [ajthinking/archetype#8]
#### setup: 
Base Laravel 6.2 installation with php-file-manipulator.

#### error description:
When trying to load in files with the documented example `PHPFile::in('database/migrations')` php-file-manipulator instantly fails with the following error message:
`Illuminate/Contracts/Filesystem/FileNotFoundException with message '/Code/database/migrations/SomeFile.php`

#### What I've tried:
1. `composer dump-autoload`
2. checked folder permissions
3. reinstalled php-file-manipulator
4. `php artisan storage:link`

**Comment by septIO** [comment]
Tried to update Laravel to `6.18.3` still no dice.
Complete stack trace can be found [here](https://flareapp.io/share/Lm8NQV7v#F44)

**Comment by ajthinking** [comment]
I just pushed a new release, last one very outdated including readme. 

With `v0.0.12` I was able to do this:
```
laravel new testy
cd testy
composer require ajthinking/php-file-manipulator
php artisan vendor:publish --provider="PHPFileManipulator\ServiceProvider"
```
and then run `PHPFile::in('database/migrations')`

**Comment by septIO** [comment]
Just tried it out with the exact commands you gave above. Still having the same issue.

**Comment by septIO** [comment]
I've been digging a little into your code.
The error seems to be https://github.com/ajthinking/php-file-manipulator/blob/463a168fef1e73b056eb0f5ba5d9e43f02ec3e6b/src/Support/PHPFileStorage.php#L20

If i return `file_get_contents($path)` instead of the code you have, it works perfectly.

So somewhere in your disk/storage management there's a bug on Windows.

**Comment by ajthinking** [comment]
Hmm, got it. What I tried to do was to enable a dynamic/configurable input/output root, inside the project or elsewhere on disk. Code is a bit of a mess, needs refactor.

**Comment by ajthinking** [comment]
Requiring UNIX based filesystem for now. Hope to fix for windows later
